language: android
jdk: oraclejdk11
before_install:
- yes | sdkmanager "platforms;android-32"

env:
  global:
    - ANDROID_API_LEVEL=32
    - ANDROID_BUILD_TOOLS_VERSION=32.0.3
    - TRAVIS_SECURE_ENV_VARS=true

android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - extra-android-m2repository
    - extra-google-android-support

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
  licenses:
    - '.+'

script:
    - ./gradlew clean
    - ./gradlew assembleDebug